//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devices()
        {
            this.Report__of_repair = new HashSet<Report__of_repair>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public string Serial_number { get; set; }
        public string Inventory_number { get; set; }
        public System.DateTime Date_of_commissioning { get; set; }
    
        public virtual Type_of_device Type_of_device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report__of_repair> Report__of_repair { get; set; }
    }
}
