//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESIR1Entities2 : DbContext
    {
        public ESIR1Entities2()
            : base("name=ESIR1Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<Report__of_repair> Report__of_repair { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Status_of_repair> Status_of_repair { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_of_device> Type_of_device { get; set; }
        public virtual DbSet<Type_of_problem> Type_of_problem { get; set; }
    }
}
